version: "3"

services:
  admin-client:
    container_name: admin-client
    build:
      context: .
      dockerfile: ./infra/docker/admin-client/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network

  user-client:
    container_name: user-client
    build:
      context: .
      dockerfile: ./infra/docker/user-client/Dockerfile
    restart: always
    ports:
      - 3001:3000
    networks:
      - app_network
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./infra/docker/server/Dockerfile
    restart: always
    ports:
      - 6969:6969
    networks:
      - app_network


networks:
  app_network:
    external: true