version: "3.8"

services:
  admin-client:
    container_name: admin-client
    build:
      context: .
      dockerfile: ./infra/docker/admin-client/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
    env_file:
      - ./apps/admin-client/.env
    depends_on:
      - server

  user-client:
    container_name: user-client
    build:
      context: .
      dockerfile: ./infra/docker/user-client/Dockerfile
    restart: always
    ports:
      - 3001:3000
    networks:
      - app_network
    env_file:
      - ./apps/user-client/.env
    depends_on:
      - server

  server:
    container_name: server
    build:
      context: .
      dockerfile: ./infra/docker/server/Dockerfile
    restart: always
    ports:
      - 6969:6969
    networks:
      - app_network
    env_file:
      - ./apps/server/.env
      
networks:
  app_network:
    external: true