- name: Deploy App
  hosts: web
  become: true

  tasks:

    - name: Ensure docker is installed
     apt:
      name: docker.io
      state: present
      update_cache: true

    - name: Pull latest image from docker hub
      shell: docker pull {{ docker_username }}/labelnet:latest

    - name: Stop and remove existing container
      shell: |
        docker stop labelnet || true
        docker rm labelnet || true

    - name: Run new container
      shell: docker run -d --name labelnet -p {{ host_port }}:{{ container_port }} --env-file .env {{ docker_username }}/labelnet:latest
    